# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'NativeJsWebView' do
  pod 'FBSDKCoreKit', '>4.9'
  # pod 'FBSDKLoginKit', '>4.9'
  # pod 'FBSDKShareKit', '>4.9'
end

